version: '3'

services:
  athenaconsumer:
    build: 
      context: athena/.
    hostname: athenaconsumer
    restart: unless-stopped
    ports:
      - "7085:7085"
    networks:
      - consumernet
    volumes:
      - ./local.properties:/src/main/resources/local.properties
      - ./private/client.truststore.jks:/src/main/resources/private/client.truststore.jks
      - ./private/server.keystore.jks:/src/main/resources/private/server.keystore.jks
    command: "java -jar build/libs/athena-3.0.jar"

  
  wcconsumer:
    build: 
      context: woocommerce/.
    hostname: wcconsumer
    restart: unless-stopped
    ports:
      - "8085:8085"
    networks:
      - consumernet
    volumes:
      - ./local.properties:/src/main/resources/local.properties
      - ./private/client.truststore.jks:/src/main/resources/private/client.truststore.jks
      - ./private/server.keystore.jks:/src/main/resources/private/server.keystore.jks
    command: "java -jar build/libs/woocommerce-3.0.jar"

  metricsconsumer:
    build: 
      context: metrics/.
    hostname: metricsconsumer
    restart: unless-stopped
    ports:
      - "9085:9085"
    networks:
      - consumernet
    volumes:
      - ./local.properties:/src/main/resources/local.properties
      - ./private/client.truststore.jks:/src/main/resources/private/client.truststore.jks
      - ./private/server.keystore.jks:/src/main/resources/private/server.keystore.jks
    command: "java -jar build/libs/metrics-3.0.jar"

volumes:
  athena:
  wc:
  metrics:

networks:
  consumernet: 
