version: '3'

services:
  athenaconsumer:
    build: 
      context: .
    hostname: athenaconsumer
    restart: unless-stopped
    ports:
      - "7085:7085"
    networks:
      - consumernet
    volumes:
      - ./local.properties:local.properties
      - ./private/client.truststore.jks:/private/client.truststore.jks
      - ./private/server.keystore.jks:/private/server.keystore.jks
  
  wcconsumer:
    build: 
      context: .
    hostname: wcconsumer
    restart: unless-stopped
    ports:
      - "8085:8085"
    networks:
      - consumernet
    volumes:
      - ./local.properties:local.properties
      - ./private/client.truststore.jks:/private/client.truststore.jks
      - ./private/server.keystore.jks:/private/server.keystore.jks

  metricsconsumer:
    build: 
      context: .
    hostname: metricsconsumer
    restart: unless-stopped
    ports:
      - "9085:9085"
    networks:
      - consumernet
    volumes:
      - ./local.properties:local.properties
      - ./private/client.truststore.jks:/private/client.truststore.jks
      - ./private/server.keystore.jks:/private/server.keystore.jks

volumes:
  athena:
  wc:
  metrics:

networks:
  consumernet: 
